services:
  moodle-app:
    image: docker.io/nfrastack/moodle:latest
    container_name: moodle-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.moodle.rule=Host(`moodle.example.com`)
      - traefik.http.services.moodle.loadbalancer.server.port=80
    volumes:
      - ./data/:/www/data
      - ./www/:/www/moodle
      - ./logs/:/logs
    environment:
      - TIMEZONE=America/Vancouver

      - DB_HOST=moodle-db
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=userpassword

## First time installation only
      - ADMIN_USER=admin
      - ADMIN_EMAIL=admin@example.domain.name
      - ADMIN_PASS=admin_password
      - SITE_URL=https://moodle.example.com
      - SITE_NAME=example_site_name
      - SITE_SHORT_NAME=example_site_short_name
##
    networks:
      - proxy
      - services
    restart: always

  moodle-db:
    image: docker.io/nfrastack/mariadb:11.8
    container_name: moodle-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TIMEZONE=America/Vancouver

      - ROOT_PASS=password
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=userpassword
    networks:
      - services
    restart: always

  moodle-db-backup:
    container_name: moodle-db-backup 
    image: docker.io/tiredofit/db-backup
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver

      - DB01_HOST=moodle-db
      - DB01_TYPE=mariadb
      - DB01_NAME=moodle
      - DB01_USER=moodle
      - DB01_PASS=userpassword
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
